# Generated by Django 3.2.9 on 2022-02-25 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Others')], max_length=20)),
                ('Country', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Published_Date', models.DateField()),
                ('Pages', models.IntegerField()),
                ('critics', models.IntegerField(default=0)),
                ('Author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='genebox.authors')),
            ],
        ),
    ]
