# Generated by Django 3.2.9 on 2022-02-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genebox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Others')], max_length=20),
        ),
    ]
