# Generated by Django 3.2.9 on 2022-03-03 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genebox', '0002_alter_authors_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='Published_Date',
            new_name='Published',
        ),
    ]
